// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xixzqfxhonamfxvlbnli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpeHpxZnhob25hbWZ4dmxibmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjU0NjcsImV4cCI6MjA2NDU0MTQ2N30.ZgEexlc1BAHYjzCHvlsgCQgDhMJ4mBIKuVlChy3j0DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);